global:
route:
  receiver: Telegram
  group_by: [alertname, instance, severity]
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 10m
  routes:
    - receiver: Telegram
      matchers:
        - instance = 'localhost:9100'
receivers:
  - name: Telegram
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token:
        chat_id: -688949245 #Get chat_id from https://api.telegram.org/botXXXXX/getUpdates
        message: |
          *Severity*: {{ .GroupLabels.severity }}
          *Alert*: {{ .GroupLabels.alertname }}
          *Status*: {{ .Status }}
        disable_notifications: false
        parse_mode: "MarkdownV2"
