groups:
- name: alert.rules.load_average
  rules:
  - alert: High Load Average
    expr: avg(node_load1{instance="localhost:9100"})*100 / count(count(node_cpu_seconds_total) by (cpu)) > 70
    for: 10s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
      summary: 'Instance {{ $labels.instance }} down.'
