groups:
- name: alert.rules.disk_space
  rules:
  - alert: Not enough free disk space
    expr: node_filesystem_avail_bytes{instance="localhost:9100",fstype="ext4"}/(1024*1024*1024) < 5
    for: 10s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
      summary: 'Instance {{ $labels.instance }} down.'
