groups:
- name: alert.rules.cpu_usage
  rules:
  - alert: High CPU usage
    expr: 100 * (1 - avg(irate(node_cpu_seconds_total{instance="localhost:9100",mode="idle"}[5m])) by (instance)) > 90
    for: 10s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
      summary: 'Instance {{ $labels.instance }} down.'
