repos:
  - id: /github.com\/avloton\/.*/
    allowed_overrides: [workflow]
    allow_custom_workflows: true
    workflow: custom
    allowed_workflows: [custom]


workflows:
  custom:
    plan:
      steps:
      - run: echo hello
      - init
      - plan:
          extra_args: ["-lock=false"]
    apply:
      steps:
      - apply
