{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Load Average 1/5/15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"localhost:9100\"})*100 / count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "Load average (1m) "
    },
    {
     "expr": "avg(node_load5{instance=\"localhost:9100\"})*100 / count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "Load average (5m) "
    },
    {
     "expr": "avg(node_load15{instance=\"localhost:9100\"})*100 / count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "Load average (15m) "
    }
   ]
  },
  {
   "title": "Free disk space in gigabytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\",fstype=\"ext4\"}/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[5m])) by (instance,cpu))",
     "legendFormat": "cpu {{cpu}}"
    },
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[5m])) by (instance))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Free RAM in megabytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}